name: main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      A32NX_PRODUCTION_BUILD: 1
      A32NX_INSTRUMENTS_BUILD_WORKERS: 2
      MAIN_PRE_RELEASE_ID: 66187913
      MAIN_PRE_RELEASE_TAG: vmain
      MAIN_ZIP_NAME: headwind-aircraft-a330-900-main.zip
      BUILD_DIR_NAME: vmain
    steps:
      - name: Delete old release assets
        uses: mknejp/delete-release-assets@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.MAIN_PRE_RELEASE_TAG }}
          assets: '*'
          fail-if-no-assets: fakse
